/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formulariografica;

import formulariografica.Formulario;
import javax.swing.JButton;

/**
 *
 * @author Admin
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        res1 = new javax.swing.JLabel();
        res2 = new javax.swing.JLabel();
        res3 = new javax.swing.JLabel();
        res4 = new javax.swing.JLabel();
        res5 = new javax.swing.JLabel();
        res6 = new javax.swing.JLabel();
        res7 = new javax.swing.JLabel();
        res8 = new javax.swing.JLabel();
        res9 = new javax.swing.JLabel();
        res10 = new javax.swing.JLabel();
        res11 = new javax.swing.JLabel();
        res12 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        res1.setText("jLabel1");

        res2.setText("jLabel1");

        res3.setText("jLabel1");

        res4.setText("jLabel1");

        res5.setText("jLabel1");

        res6.setText("jLabel1");

        res7.setText("jLabel1");

        res8.setText("jLabel1");

        res9.setText("jLabel1");

        res10.setText("jLabel1");

        res11.setText("jLabel1");

        res12.setText("jLabel1");

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 0, 0));
        titulo.setText("Informações");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(res1)
                            .addComponent(res2)
                            .addComponent(res3)
                            .addComponent(res4)
                            .addComponent(res5)
                            .addComponent(res6)
                            .addComponent(res7)
                            .addComponent(res8)
                            .addComponent(res9)
                            .addComponent(res10)
                            .addComponent(res11)
                            .addComponent(res12)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(titulo)))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addComponent(res1)
                .addGap(18, 18, 18)
                .addComponent(res2)
                .addGap(18, 18, 18)
                .addComponent(res3)
                .addGap(18, 18, 18)
                .addComponent(res4)
                .addGap(18, 18, 18)
                .addComponent(res5)
                .addGap(18, 18, 18)
                .addComponent(res6)
                .addGap(18, 18, 18)
                .addComponent(res7)
                .addGap(18, 18, 18)
                .addComponent(res8)
                .addGap(18, 18, 18)
                .addComponent(res9)
                .addGap(18, 18, 18)
                .addComponent(res10)
                .addGap(18, 18, 18)
                .addComponent(res11)
                .addGap(18, 18, 18)
                .addComponent(res12)
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel res1;
    public javax.swing.JLabel res10;
    public javax.swing.JLabel res11;
    public javax.swing.JLabel res12;
    public javax.swing.JLabel res2;
    public javax.swing.JLabel res3;
    public javax.swing.JLabel res4;
    public javax.swing.JLabel res5;
    public javax.swing.JLabel res6;
    public javax.swing.JLabel res7;
    public javax.swing.JLabel res8;
    public javax.swing.JLabel res9;
    public javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
